#!/usr/bin/env python3
"""GI & Hepatology Weekly — guidelines, consensus statements & clinical studies.

Weekly GitHub Actions digest:

  1. Fetch newly indexed PubMed items in the last N days (default 14) across
     four queries: GI/hepatology-journal guidelines, topic-based (MeSH)
     guidelines, GI/hepatology-journal trials/meta-analyses, and major general
     journals carrying GI/hepatology major-topic trials. Europe PMC is the
     fallback source tier.
  2. Analyse every item with Gemini Flash + Extended Thinking (webapi /
     cookie auth via gemini.py; a free-tier API key is used as a fallback
     backend so a dead cookie never kills the digest).
  3. Render two conclusion infographics: a matplotlib evidence-mix chart
     (local, exact) and a comprehensive clinical infographic generated by
     Gemini NotebookLM from the item sources.
  4. Email a single HTML report (text summary + both infographics).

No ranking, no scoring anywhere — the reader gets the evidence, its numbers
and its practice implication.

Env knobs are documented in README.md / AGENTS.md. Key ones:
  RUN_BACK_DAYS (14), ANALYSIS_MAX_ITEMS (34), GEMINI_MODEL (flash),
  GEMINI_THINKING (extended), GEMINI_API_KEY (fallback backend),
  FETCH_SOURCE (auto|pubmed|epmc), DIGEST_DRY_RUN (1 = no email).
"""
from __future__ import annotations

import gzip  # noqa: F401  (kept for parity with sibling digests / key checks)
import html as _html
import json
import os
import re
import smtplib
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta, timezone
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STATE_FILE = os.path.join(SCRIPT_DIR, "state", "seen_ids.json")
OUT_DIR = os.environ.get("DIGEST_OUT_DIR",
                         os.path.expanduser("~/.hermes/digest_images"))

# ── Config ───────────────────────────────────────────────────────────────────
WINDOW_DAYS = int(os.environ.get("RUN_BACK_DAYS") or 14)
MAX_GUIDE_CANDIDATES = int(os.environ.get("MAX_GUIDE_CANDIDATES") or 25)
MAX_TRIAL_CANDIDATES = int(os.environ.get("MAX_TRIAL_CANDIDATES") or 15)
ANALYSIS_MAX_ITEMS = int(os.environ.get("ANALYSIS_MAX_ITEMS") or 34)
ABSTRACT_CHARS = int(os.environ.get("ABSTRACT_CHARS") or 1500)
BATCH_SIZE = int(os.environ.get("BATCH_SIZE") or 18)
SEEN_KEEP_DAYS = int(os.environ.get("SEEN_KEEP_DAYS") or 120)
BREAKING_LIMIT = int(os.environ.get("BREAKING_LIMIT") or 10)

GEMINI_SCRIPT = os.environ.get(
    "GEMINI_SCRIPT", os.path.join(SCRIPT_DIR, "gemini.py"))
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "flash")
GEMINI_THINKING = os.environ.get("GEMINI_THINKING", "extended")
GEMINI_TIMEOUT = int(os.environ.get("GEMINI_TIMEOUT") or 300)
GEMINI_RETRIES = int(os.environ.get("GEMINI_RETRIES") or 2)
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
GEMINI_API_MODELS = [
    m for m in (os.environ.get("GEMINI_API_MODEL", "gemini-3.5-flash"),
                "gemini-flash-lite-latest", "gemini-2.5-flash") if m]
DIGEST_LANG = os.environ.get("DIGEST_LANG", "en").strip() or "en"
FETCH_SOURCE = (os.environ.get("FETCH_SOURCE") or "auto").strip().lower()

SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT") or 465)
SMTP_USER = os.environ.get("SMTP_USER", "")
RECIPIENT = os.environ.get("RECIPIENT", "")

EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
EPMC = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
UA = ("gi-hep-gem-digest/1.0 (+https://github.com/lesterppo/"
      "gi-hep-gem-digest)")
HTTP_TRIES = int(os.environ.get("HTTP_TRIES") or 4)

# ── Query surface ────────────────────────────────────────────────────────────
GI_JOURNALS = [
    "Gut", "Gastroenterology", "J Hepatol", "Hepatology", "Am J Gastroenterol",
    "Clin Gastroenterol Hepatol", "J Crohns Colitis", "Endoscopy",
    "Gastrointest Endosc", "Aliment Pharmacol Ther", "Liver Int",
    "J Gastroenterol Hepatol", "Therap Adv Gastroenterol",
    "United European Gastroenterol J", "Hepatol Int", "Clin Mol Hepatol",
    "JHEP Rep", "J Gastroenterol", "Dig Endosc", "Neurogastroenterol Motil",
    "Liver Transpl", "Inflamm Bowel Dis", "Dig Liver Dis",
    "Eur J Gastroenterol Hepatol", "HPB (Oxford)", "Pancreatology",
    "J Clin Gastroenterol", "BMC Gastroenterol", "Ann Hepatol",
    "World J Gastroenterol", "Clin Transl Gastroenterol", "Hepatol Commun",
]
GEN_JOURNALS = [
    "N Engl J Med", "Lancet", "Lancet Gastroenterol Hepatol", "JAMA",
    "Nat Med", "Ann Intern Med", "Nat Rev Gastroenterol Hepatol", "BMJ",
]
GI_MESH = [
    "Gastrointestinal Diseases", "Liver Diseases",
    "Gastrointestinal Neoplasms", "Inflammatory Bowel Diseases",
    "Pancreatic Diseases", "Biliary Tract Diseases", "Hepatitis",
    "Gastroenterology", "Hepatology", "Colorectal Neoplasms",
    "Esophageal Diseases", "Stomach Diseases", "Cholestasis",
    "Liver Cirrhosis", "Fatty Liver",
]
GUIDE_PUBTYPES = ["guideline", "practice guideline",
                  "consensus development conference",
                  "consensus development conference, nih"]
TRIAL_PUBTYPES = ["randomized controlled trial", "meta-analysis",
                  "systematic review", "clinical trial, phase iii",
                  "controlled clinical trial", "clinical trial, phase ii"]
TITLE_GUIDE_RE = re.compile(
    r"\b(guideline|guidance|consensus|position statement|recommendation|"
    r"recommendations|delphi|expert review|clinical practice update|"
    r"white paper|standards of practice)\b", re.I)
SOCIETY_RE = re.compile(
    r"\b(ESGE|ESGAR|EASL|AASLD|ACG|AGA|ASGE|BSG|APAGE|ESMO|ECCO|ESPGHAN|"
    r"NASPGHAN|WGO|UEG|EASD|AISF|AISP|JSGE|JSH|KASL|KLCA|CSCO|NICE|"
    r"Asian Pacific Association|American College of Gastroenterology|"
    r"American Gastroenterological Association|European Association for the "
    r"Study of the Liver|European Society of Gastrointestinal Endoscopy|"
    r"British Society of Gastroenterology|Asian Pacific Association for the "
    r"Study of the Liver|World Gastroenterology Organisation|"
    r"American Society for Gastrointestinal Endoscopy)\b")


def log(msg: str) -> None:
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}", flush=True)


# ── HTTP ─────────────────────────────────────────────────────────────────────
def _retry_after(msg: str) -> float | None:
    m = re.search(r"retry-after[:\s]+(\d+)", msg, re.I)
    return float(m.group(1)) if m else None


def http_get(url: str, timeout: int = 45, tries: int = HTTP_TRIES) -> bytes:
    """GET with a retry ladder (429/5xx/transient), honouring Retry-After."""
    last = ""
    for attempt in range(1, tries + 1):
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": UA, "Accept": "*/*"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            body = ""
            try:
                body = e.read().decode("utf-8", "replace")[:200]
            except Exception:
                pass
            last = f"HTTP {e.code}: {body or e.reason}"
            retryable = e.code == 429 or 500 <= e.code < 600
            if not retryable or attempt == tries:
                break
            wait = _retry_after(f"{e.headers.get('Retry-After', '')} ") \
                or 3.0 * attempt
            log(f"  http {e.code} — retry in {wait:.0f}s ({url[:90]})")
            time.sleep(min(wait, 45))
        except Exception as e:  # noqa: BLE001 — transient socket/timeouts
            last = f"{type(e).__name__}: {e}"
            if attempt == tries:
                break
            wait = 2.0 * attempt
            log(f"  http transient ({last[:80]}) — retry in {wait:.0f}s")
            time.sleep(wait)
    raise RuntimeError(f"GET failed after {tries} tries: {url[:110]} — {last}")


def http_post(url: str, data: bytes, content_type: str,
              timeout: int = 45, tries: int = HTTP_TRIES) -> bytes:
    last = ""
    for attempt in range(1, tries + 1):
        try:
            req = urllib.request.Request(url, data=data, headers={
                "User-Agent": UA, "Content-Type": content_type,
                "Accept": "*/*"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            body = ""
            try:
                body = e.read().decode("utf-8", "replace")[:200]
            except Exception:
                pass
            last = f"HTTP {e.code}: {body or e.reason}"
            if not (e.code == 429 or 500 <= e.code < 600) or attempt == tries:
                break
            time.sleep(min(_retry_after(
                f"{e.headers.get('Retry-After','')} ") or 3.0 * attempt, 45))
        except Exception as e:  # noqa: BLE001
            last = f"{type(e).__name__}: {e}"
            if attempt == tries:
                break
            time.sleep(2.0 * attempt)
    raise RuntimeError(f"POST failed after {tries} tries: {url[:110]} — {last}")


# ── Fetch: PubMed (tier 1) ───────────────────────────────────────────────────
def _or_field(field: str, values: list[str]) -> str:
    return "(" + " OR ".join(f'"{v}"{field}' for v in values) + ")"


def _queries() -> list[dict]:
    jour = _or_field("[jour]", GI_JOURNALS)
    genj = _or_field("[jour]", GEN_JOURNALS)
    mesh = _or_field("[MeSH]", GI_MESH)
    mesh_major = _or_field("[MeSH Major Topic]", GI_MESH)
    guide = _or_field("[pt]", GUIDE_PUBTYPES)
    trial = _or_field("[pt]", TRIAL_PUBTYPES)
    title_guide = ("(" + " OR ".join(
        f'"{t}"[ti]' for t in ("guideline", "guidelines", "consensus",
                              "recommendations", "position statement",
                              "clinical practice update", "expert review")
    ) + ")")
    return [
        # Guidelines / consensus, GI-hepatology journals
        {"name": "guide_journal", "kind": "guideline",
         "max": MAX_GUIDE_CANDIDATES,
         "term": f"(({guide}) OR ({title_guide})) AND ({jour})"},
        # Guidelines / consensus on GI-hepatology topics, any indexed journal
        {"name": "guide_topic", "kind": "guideline",
         "max": MAX_GUIDE_CANDIDATES,
         "term": f"(({guide}) OR ({title_guide})) AND ({mesh})"},
        # Trials / meta-analyses / systematic reviews, GI-hepatology journals
        {"name": "trial_journal", "kind": "trial",
         "max": MAX_TRIAL_CANDIDATES,
         "term": f"({trial}) AND ({jour})"},
        # Major general journals carrying GI-hepatology major-topic trials
        {"name": "trial_general", "kind": "trial",
         "max": max(6, MAX_TRIAL_CANDIDATES // 2),
         "term": f"({trial}) AND ({genj}) AND ({mesh_major})"},
    ]


def _pubdate_str(node) -> str:
    """PubDate/ArticleDate element -> ISO date string (best effort)."""
    if node is None:
        return ""
    y = (node.findtext("Year") or "").strip()
    if not y:
        medline = (node.findtext("MedlineDate") or "").strip()
        m = re.search(r"(19|20)\d{2}", medline)
        return m.group(0) if m else ""
    mon = (node.findtext("Month") or "").strip()
    day = (node.findtext("Day") or "").strip()
    mm = "01"
    if mon:
        names = ("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug",
                 "sep", "oct", "nov", "dec")
        low = mon.lower()[:3]
        mm = (f"{names.index(low) + 1:02d}" if low in names
              else (mon.zfill(2) if mon.isdigit() else "01"))
    return f"{y}-{mm}-{day.zfill(2) if day.isdigit() else '01'}"


def parse_pubmed_xml(xml_bytes: bytes) -> list[dict]:
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError as e:
        raise RuntimeError(f"PubMed XML parse error: {e}") from e
    items: list[dict] = []
    for pa in root.iter("PubmedArticle"):
        cit = pa.find("MedlineCitation")
        if cit is None:
            continue
        pmid = (cit.findtext("PMID") or "").strip()
        art = cit.find("Article")
        if art is None or not pmid:
            continue
        title = re.sub(r"\s+", " ", "".join(
            (art.find("ArticleTitle").itertext()
             if art.find("ArticleTitle") is not None else ""))).strip()
        journal = ""
        pubdate = epub = ""
        j = art.find("Journal")
        if j is not None:
            journal = (j.findtext("ISOAbbreviation")
                       or j.findtext("Title") or "").strip()
            ji = j.find("JournalIssue")
            if ji is not None:
                pubdate = _pubdate_str(ji.find("PubDate"))
        ad = art.find("ArticleDate")
        if ad is not None:
            epub = _pubdate_str(ad)
        parts = []
        for at in art.findall(".//Abstract/AbstractText"):
            label = (at.get("Label") or "").strip()
            txt = re.sub(r"\s+", " ", "".join(at.itertext())).strip()
            if not txt:
                continue
            parts.append(f"{label}: {txt}" if label else txt)
        abstract = " ".join(parts)
        doi = ""
        for el in art.findall("ELocationID"):
            if (el.get("EIdType") or "").lower() == "doi":
                doi = (el.text or "").strip()
        authors = []
        for a in art.findall(".//AuthorList/Author"):
            ln = (a.findtext("LastName") or "").strip()
            ini = (a.findtext("Initials") or "").strip()
            if ln:
                authors.append(f"{ln} {ini}".strip())
            elif (a.findtext("CollectiveName") or "").strip():
                authors.append(a.findtext("CollectiveName").strip())
        pubtypes = [(pt.text or "").strip()
                    for pt in cit.findall(".//PublicationTypeList/PublicationType")]
        items.append({
            "pmid": pmid, "title": title, "journal": journal,
            "date": epub or pubdate, "doi": doi, "authors": authors,
            "abstract": abstract, "pubtypes": pubtypes, "source": "pubmed",
        })
    return items


def fetch_pubmed(start: datetime, end: datetime) -> tuple[list[dict], list[str]]:
    """Four E-utilities searches -> parsed, deduped items. Returns (items, errors)."""
    errors: list[str] = []
    by_pmid: dict[str, dict] = {}
    for q in _queries():
        try:
            params = urllib.parse.urlencode({
                "db": "pubmed", "term": q["term"], "retmode": "json",
                "retmax": q["max"], "datetype": "edat",
                "reldate": WINDOW_DAYS, "sort": "pub_date"})
            d = json.loads(http_get(f"{EUTILS}esearch.fcgi?{params}").decode())
            res = d.get("esearchresult", {})
            ids = [i for i in res.get("idlist", []) if i]
            log(f"  {q['name']}: {res.get('count')} hit(s), "
                f"{len(ids)} fetched (max {q['max']})")
            if not ids:
                continue
            xml = http_post(
                f"{EUTILS}efetch.fcgi",
                urllib.parse.urlencode({
                    "db": "pubmed", "id": ",".join(ids),
                    "retmode": "xml", "rettype": "abstract"}).encode(),
                "application/x-www-form-urlencoded", timeout=90)
            for it in parse_pubmed_xml(xml):
                it["kind"] = classify_kind(it)
                it["query"] = q["name"]
                if it["pmid"] not in by_pmid:
                    by_pmid[it["pmid"]] = it
            time.sleep(0.4)  # be polite to E-utilities
        except Exception as e:  # noqa: BLE001
            msg = f"pubmed {q['name']}: {type(e).__name__}: {e}"
            log(f"  ERROR {msg}")
            errors.append(msg)
    return list(by_pmid.values()), errors


def classify_kind(it: dict) -> str:
    pts = " ".join(it.get("pubtypes") or []).lower()
    t = (it.get("title") or "").lower()
    if "guideline" in pts or "consensus development conference" in pts:
        return "guideline"
    if re.search(r"\b(guideline|guidance|position statement|delphi|"
                 r"clinical practice update|standards of practice)\b", t):
        return "guideline"
    if "consensus" in t or re.search(r"\bexpert (consensus|review)\b", t):
        return "consensus"
    if "meta-analysis" in pts or "meta-analysis" in t:
        return "meta-analysis"
    if "systematic review" in pts or "systematic review" in t:
        return "systematic review"
    if "randomized controlled trial" in pts or "controlled clinical trial" in pts \
            or "clinical trial, phase" in pts:
        return "trial"
    if re.search(r"\b(randomi[sz]ed|randomi[sz]ed controlled|phase (1|2|3|ii|iii))\b", t):
        return "trial"
    return "study"


# ── Fetch: Europe PMC (tier 2) ───────────────────────────────────────────────
def fetch_epmc(start: datetime, end: datetime) -> tuple[list[dict], list[str]]:
    s, e = start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")
    jour = " OR ".join(f'JOURNAL:"{j}"' for j in GI_JOURNALS)
    guid = ('(PUB_TYPE:"Practice Guideline" OR PUB_TYPE:"Guideline" OR '
            'TITLE:"consensus" OR TITLE:"guideline" OR TITLE:"guidelines" OR '
            'TITLE:"recommendations" OR TITLE:"position statement")')
    trials = ('(PUB_TYPE:"Randomized Controlled Trial" OR '
              'PUB_TYPE:"Meta-Analysis" OR PUB_TYPE:"Systematic Review" OR '
              'PUB_TYPE:"Clinical Trial" OR PUB_TYPE:"Review")')
    mesh = ' OR '.join(f'MESH:"{m}"' for m in GI_MESH)
    queries = [
        ("guide_journal", f"{guid} AND ({jour})"),
        ("guide_topic", f"{guid} AND ({mesh})"),
        ("trial_journal", f"{trials} AND ({jour})"),
    ]
    errors: list[str] = []
    by_pmid: dict[str, dict] = {}
    cap = {"guide_journal": MAX_GUIDE_CANDIDATES,
           "guide_topic": MAX_GUIDE_CANDIDATES,
           "trial_journal": MAX_TRIAL_CANDIDATES}
    for name, q in queries:
        try:
            params = urllib.parse.urlencode({
                "query": f'({q}) AND FIRST_PDATE:[{s} TO {e}] AND SRC:MED',
                "format": "json", "resultType": "core",
                "pageSize": cap[name]})
            d = json.loads(http_get(f"{EPMC}?{params}", timeout=60).decode())
            rows = d.get("resultList", {}).get("result", [])
            log(f"  epmc {name}: {d.get('hitCount')} hit(s), {len(rows)} fetched")
            for r in rows:
                pmid = str(r.get("pmid") or r.get("id") or "").strip()
                if not pmid:
                    continue
                ji = (r.get("journalInfo") or {})
                jrec = (ji.get("journal") or {})
                journal = (jrec.get("title") or jrec.get("medlineAbbreviation")
                           or "").strip()
                pts = (r.get("pubTypeList") or {}).get("pubType") or []
                it = {
                    "pmid": pmid,
                    "title": re.sub(r"\s+", " ", r.get("title") or "").strip(),
                    "journal": journal,
                    "date": str(r.get("firstPublicationDate")
                                or r.get("firstIndexDate") or "")[:10],
                    "doi": r.get("doi") or "",
                    "authors": [],
                    "abstract": re.sub(r"\s+", " ",
                                       r.get("abstractText") or "").strip(),
                    "pubtypes": [str(p) for p in pts],
                    "source": "europepmc", "query": name,
                }
                it["kind"] = classify_kind(it)
                if it["pmid"] not in by_pmid:
                    by_pmid[it["pmid"]] = it
            time.sleep(0.3)
        except Exception as e:  # noqa: BLE001
            msg = f"epmc {name}: {type(e).__name__}: {e}"
            log(f"  ERROR {msg}")
            errors.append(msg)
    return list(by_pmid.values()), errors


# ── Selection / dedup ────────────────────────────────────────────────────────
def _load_seen() -> dict:
    try:
        with open(STATE_FILE, encoding="utf-8") as f:
            d = json.load(f)
        return d if isinstance(d, dict) else {}
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _save_seen(seen: dict) -> None:
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(seen, f, indent=0)


def _prune_seen(seen: dict) -> dict:
    cutoff = (datetime.now(timezone.utc) - timedelta(days=SEEN_KEEP_DAYS)) \
        .strftime("%Y-%m-%d")
    return {k: v for k, v in seen.items() if str(v) >= cutoff}


KIND_ORDER = {"guideline": 0, "consensus": 1, "meta-analysis": 2,
              "systematic review": 3, "trial": 4, "study": 5}


def select_items(items: list[dict], seen: dict) -> tuple[list[dict], list[dict], list[dict]]:
    """Split into (to_analyse, already_seen, dropped_for_capacity)."""
    fresh = [it for it in items if it["pmid"] not in seen]
    dupes = [it for it in items if it["pmid"] in seen]
    # guidance before studies; newest first inside each kind group
    fresh.sort(key=lambda x: (KIND_ORDER.get(x["kind"], 9),
                              _neg_date(x.get("date") or "")))
    kept = fresh[:ANALYSIS_MAX_ITEMS]
    dropped = fresh[ANALYSIS_MAX_ITEMS:]
    return kept, dupes, dropped


def _neg_date(d: str) -> str:
    """Sort key that puts newer ISO dates first inside a group."""
    return "".join(chr(ord("9") - (ord(c) - ord("0")))
                   if c.isdigit() else c for c in (d or "0000-00-00"))


# ── Gemini (web first, free API key fallback) ────────────────────────────────
def setup_auth_from_env() -> None:
    sid = os.environ.get("GEMINI_SID")
    ts = os.environ.get("GEMINI_TS")
    if not sid or not ts:
        return
    d = os.path.expanduser("~/.gemini-cli")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "auth.json"), "w") as f:
        json.dump({"__Secure-1PSID": sid, "__Secure-1PSIDTS": ts}, f)


def _gemini_web(prompt: str, batch_label: str) -> dict:
    """Gemini Flash + Extended Thinking through gemini.py (cookie auth)."""
    out_path = os.path.join(SCRIPT_DIR, "state", f"digest_{batch_label}.md")
    args = [sys.executable, GEMINI_SCRIPT, "-m", GEMINI_MODEL,
            "--thinking", GEMINI_THINKING, "--raw", "--brief",
            "-o", out_path, "-p", prompt]
    env = dict(os.environ, PYTHONUNBUFFERED="1")
    last = ""
    for attempt in range(1, GEMINI_RETRIES + 2):
        try:
            proc = subprocess.run(args, capture_output=True, text=True,
                                  env=env, timeout=GEMINI_TIMEOUT)
            out = (proc.stdout or "").strip()
            try:
                parsed = json.loads(out) if out else {}
            except json.JSONDecodeError:
                parsed = {}
            if parsed.get("ok"):
                f = parsed.get("f")
                if f and os.path.exists(f):
                    with open(f, encoding="utf-8") as fh:
                        return {"ok": True, "text": fh.read(), "backend": "web"}
                return {"ok": True, "text": parsed.get("text", ""),
                        "backend": "web"}
            last = (parsed.get("err") or proc.stderr.strip() or out[:300]
                    or "unknown")
            if attempt <= GEMINI_RETRIES:
                log(f"  gemini(web) attempt {attempt} err {last[:120]} — retry")
                time.sleep(8 * attempt)
        except subprocess.TimeoutExpired:
            last = "TIMEOUT"
            if attempt <= GEMINI_RETRIES:
                log(f"  gemini(web) attempt {attempt} timeout — retry")
                time.sleep(8 * attempt)
    return {"ok": False, "err": last, "backend": "web"}


def _gemini_api(prompt: str) -> dict:
    """Fallback backend: free-tier AI Studio API key (no browser, no cookies)."""
    if not GEMINI_API_KEY:
        return {"ok": False, "err": "NO_API_KEY", "backend": "api"}
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "maxOutputTokens": 65536,
            "thinkingConfig": {"thinkingBudget": 16384,
                               "includeThoughts": False},
        },
    }
    last = ""
    for model in GEMINI_API_MODELS:
        for attempt in (1, 2):
            try:
                req = urllib.request.Request(
                    "https://generativelanguage.googleapis.com/v1beta/models/"
                    f"{model}:generateContent",
                    data=json.dumps(body).encode(),
                    headers={"Content-Type": "application/json",
                             "x-goog-api-key": GEMINI_API_KEY})
                with urllib.request.urlopen(req, timeout=GEMINI_TIMEOUT) as r:
                    d = json.load(r)
                cands = d.get("candidates") or []
                if not cands:
                    last = f"{model}: no candidates ({str(d)[:160]})"
                    continue
                text = "".join(p.get("text", "")
                               for p in cands[0].get("content", {})
                               .get("parts", []))
                if not text.strip():
                    last = (f"{model}: empty text "
                            f"(finishReason={cands[0].get('finishReason')})")
                    continue
                log(f"  gemini(api) ok via {model}")
                return {"ok": True, "text": text, "backend": f"api:{model}"}
            except urllib.error.HTTPError as e:
                detail = ""
                try:
                    detail = e.read().decode("utf-8", "replace")[:200]
                except Exception:
                    pass
                last = f"{model} HTTP {e.code}: {detail}"
                if e.code in (429, 500, 503) and attempt == 1:
                    time.sleep(6)
                    continue
                break
            except Exception as e:  # noqa: BLE001
                last = f"{model} {type(e).__name__}: {e}"
                if attempt == 1:
                    time.sleep(4)
                    continue
                break
    return {"ok": False, "err": last or "unknown", "backend": "api"}


def gemini_analyze(prompt: str, batch_label: str) -> dict:
    """Web (Flash + Extended) first; fall back to the API-key backend."""
    if FETCH_SOURCE not in ("api_only",):
        res = _gemini_web(prompt, batch_label)
        if res.get("ok"):
            return res
        log(f"  gemini(web) failed: {str(res.get('err'))[:140]} — "
            f"falling back to API key backend")
    else:
        res = {"ok": False, "err": "skipped-by-config"}
    api = _gemini_api(prompt)
    if api.get("ok"):
        return api
    return {"ok": False, "err": f"web={res.get('err')} api={api.get('err')}"}


# ── Analysis prompt ──────────────────────────────────────────────────────────
LANG_LINE = {
    "zh": ("Write the whole report in Traditional Chinese (Hong Kong), keeping "
           "drug, society and journal names in English."),
    "zh-hant": ("Write the whole report in Traditional Chinese (Hong Kong), "
                "keeping drug, society and journal names in English."),
}


def build_prompt(items: list[dict], part: int, n_parts: int) -> str:
    date_label = datetime.now().strftime("%Y-%m-%d")
    head = [
        "You are the evidence-scanning engine for a WEEKLY clinical digest of "
        "gastroenterology and hepatology literature, read by hospital-based "
        "gastroenterologists and hepatologists.",
        "",
        f"Today is {date_label}. Below are {len(items)} items newly indexed in "
        f"PubMed over the last {WINDOW_DAYS} days: clinical practice guidelines, "
        "expert consensus statements, randomised trials, meta-analyses and "
        "systematic reviews.",
        "",
        "Output REQUIRED structure (part "
        f"{part} of {n_parts}):" if n_parts > 1 else
        "Output REQUIRED structure:",
    ]
    if n_parts > 1 and part == 1:
        head.append(
            "Start with the '## Week in focus' and '## Guideline watch' "
            "sections, then the item blocks.")
    elif n_parts > 1:
        head.append("Output ONLY the item blocks (no week-in-focus section).")
    else:
        head.append(
            "Start with '## Week in focus', then '## Guideline watch', then "
            "the item blocks.")
    head += [
        "",
        "## Week in focus",
        "- 3-5 bullets: the developments that would most change practice this "
        "week. Each bullet names the issuing body or journal and the PMID.",
        "",
        "## Guideline watch",
        "- one line naming the societies/bodies that issued new or updated "
        "guidance this week, or the single word: none",
        "",
        "Then one block per item, EXACTLY this shape:",
        "",
        "### <short title, max 90 characters>",
        "- **Citation**: <Journal> - <date> - PMID <pmid> "
        "(https://pubmed.ncbi.nlm.nih.gov/<pmid>/)",
        "- **Type**: <Clinical practice guideline | Expert consensus | "
        "Randomised trial | Meta-analysis | Systematic review | Study>",
        "- **What it says**: 2-3 sentences with the ACTUAL recommendations or "
        "findings and their key numbers - effect sizes with 95% CI, HR/OR/RR, "
        "absolute differences, event counts, N, endpoints (survival, "
        "clinical remission, SVR, rebleeding, etc.). Never report p-values.",
        "- **Practice impact**: one line - what a gastroenterologist or "
        "hepatologist should do differently, or state plainly 'no change to "
        "current practice - supports it'.",
        "- **Caveat**: one line on the main limitation (single-centre, "
        "surrogate endpoint, retrospective, industry-funded, short follow-up, "
        "abstract truncated, etc.).",
        "",
        "Ordering: guidelines and consensus statements first (in the order "
        "given), then trials, meta-analyses and reviews.",
        "",
        "Rules:",
        "- Base every statement ONLY on the abstract text supplied below. "
        "Never invent recommendations, numbers, societies, drug names or "
        "durations.",
        "- If an abstract is missing or clearly truncated, write "
        "'abstract truncated - verify full text' inside the Caveat line.",
        "- Prefer concrete clinical language over generic praise; skip empty "
        "phrases like 'important study'.",
        "- No scores, no ratings, no rankings, no grade letters anywhere.",
        "- Do not add a summary of your own at the end.",
    ]
    if LANG_LINE.get(DIGEST_LANG.lower()):
        head.append("- " + LANG_LINE[DIGEST_LANG.lower()])
    head += ["", "Items:", ""]
    for it in items:
        ab = (it.get("abstract") or "")[:ABSTRACT_CHARS]
        authors = it.get("authors") or []
        au = ", ".join(authors[:3]) + (" et al." if len(authors) > 3 else "")
        head.append(f"### {it['kind'].upper()} | PMID {it['pmid']}")
        head.append(f"Title: {it['title']}")
        head.append(f"Journal: {it.get('journal','?')} | "
                    f"Date: {it.get('date','?')} | Query: {it.get('query','')}")
        if au:
            head.append(f"Authors: {au}")
        head.append(f"Abstract: {ab if ab else '(no abstract available)'}")
        head.append("")
    return "\n".join(head)


def analyze(items: list[dict]) -> dict:
    batches = [items[i:i + BATCH_SIZE]
               for i in range(0, len(items), BATCH_SIZE)] or [[]]
    texts, backends, errors = [], [], []
    for i, b in enumerate(batches, 1):
        if not b:
            continue
        log(f"Gemini analysis batch {i}/{len(batches)} ({len(b)} items)")
        t0 = time.time()
        res = gemini_analyze(build_prompt(b, i, len(batches)), f"b{i}")
        if res.get("ok") and res.get("text", "").strip():
            texts.append(res["text"].strip())
            backends.append(res.get("backend", "?"))
            log(f"  batch {i} ok via {res.get('backend')} "
                f"({len(res['text'])} chars, {time.time()-t0:.0f}s)")
        else:
            errors.append(f"batch {i}: {str(res.get('err'))[:200]}")
            log(f"  batch {i} FAILED: {str(res.get('err'))[:200]}")
    return {"text": "\n\n".join(texts), "backends": backends,
            "errors": errors, "ok": bool(texts)}


# ── Infographic 1: matplotlib evidence mix ───────────────────────────────────
def _trunc(s: str, n: int) -> str:
    """Truncate a label with an ellipsis so clipping is never ambiguous."""
    s = (s or "").strip()
    return s if len(s) <= n else s[:n - 1].rstrip() + "\u2026"

def render_evidence_chart(items: list[dict], out_dir: str) -> str:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from collections import Counter

    kind_labels = {
        "guideline": "Guideline / practice update",
        "consensus": "Expert consensus",
        "trial": "Randomised / controlled trial",
        "meta-analysis": "Meta-analysis",
        "systematic review": "Systematic review",
        "study": "Other study",
    }
    kc = Counter(it["kind"] for it in items)
    kinds = [k for k in ("guideline", "consensus", "trial", "meta-analysis",
                         "systematic review", "study") if kc.get(k)]
    jc = Counter((it.get("journal") or "?").strip() for it in items)
    jtop = jc.most_common(8)[::-1]
    soc = Counter()
    for it in items:
        for m in SOCIETY_RE.findall(it.get("title", "") + " " +
                                    (it.get("abstract") or "")[:400]):
            soc[m] += 1
    stop = soc.most_common(6)[::-1]

    ncol = 3 if stop else 2
    fig, axes = plt.subplots(1, ncol, figsize=(5.6 * ncol, 5.0), dpi=200)
    fig.patch.set_facecolor("#f7f9fb")
    for ax in axes:
        ax.set_facecolor("#ffffff")
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
        ax.tick_params(colors="#33414f", labelsize=9)

    ax = axes[0]
    vals = [kc[k] for k in kinds]
    labels = [kind_labels[k] for k in kinds]
    colors = ["#1e4e79" if k in ("guideline", "consensus") else "#2e8b8b"
              for k in kinds]
    ax.barh(range(len(kinds)), vals, color=colors, height=0.62)
    ax.set_yticks(range(len(kinds)))
    ax.set_yticklabels(labels)
    for i, v in enumerate(vals):
        ax.text(v + 0.08, i, str(v), va="center", fontsize=9,
                color="#33414f", fontweight="bold")
    ax.set_xlim(0, max(vals) * 1.22)
    ax.set_title("Evidence type mix", fontsize=11, color="#1e4e79",
                 fontweight="bold", loc="left")
    ax.set_xticks([])

    ax = axes[1]
    ax.barh(range(len(jtop)), [c for _, c in jtop], color="#7aa6c2",
            height=0.62)
    ax.set_yticks(range(len(jtop)))
    ax.set_yticklabels([_trunc(j, 24) for j, _ in jtop], fontsize=8)
    for i, (_, c) in enumerate(jtop):
        ax.text(c + 0.06, i, str(c), va="center", fontsize=8,
                color="#33414f", fontweight="bold")
    ax.set_xlim(0, max(c for _, c in jtop) * 1.25)
    ax.set_title("Journals represented", fontsize=11, color="#1e4e79",
                 fontweight="bold", loc="left")
    ax.set_xticks([])

    if stop:
        ax = axes[2]
        ax.barh(range(len(stop)), [c for _, c in stop], color="#c98b3a",
                height=0.62)
        ax.set_yticks(range(len(stop)))
        ax.set_yticklabels([_trunc(s, 24) for s, _ in stop], fontsize=8)
        for i, (_, c) in enumerate(stop):
            ax.text(c + 0.05, i, str(c), va="center", fontsize=8,
                    color="#33414f", fontweight="bold")
        ax.set_xlim(0, max(c for _, c in stop) * 1.3)
        ax.set_title("Issuing bodies mentioned", fontsize=11, color="#1e4e79",
                     fontweight="bold", loc="left")
        ax.set_xticks([])

    fig.suptitle("GI & Hepatology Weekly - evidence mix", fontsize=14,
                 color="#12283d", fontweight="bold", x=0.02, ha="left")
    win = (f"Window: last {WINDOW_DAYS} days  |  {len(items)} items analysed  |"
           f"  generated {datetime.now():%Y-%m-%d %H:%M}")
    fig.text(0.02, 0.015, win, fontsize=8.5, color="#5b6b7c", ha="left")
    fig.subplots_adjust(left=0.24, right=0.98, top=0.86, bottom=0.09,
                        wspace=0.55)
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, f"gihep_chart_{datetime.now():%Y%m%d-%H%M}.png")
    fig.savefig(out, facecolor=fig.get_facecolor())
    plt.close(fig)
    return out



# ── Infographic fallback: clinical poster (no auth needed) ───────────────────
def render_clinical_poster(items: list, digest_text: str, date_range: str,
                           out_dir: str) -> str:
    """Text-and-layout clinical poster rendered locally.

    The NotebookLM dashboard needs a live browser session; this keeps the
    promise that every digest carries a comprehensive infographic even when
    that session is stale (the evidence-mix chart alone is not a summary)."""
    from textwrap import wrap
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle

    WIDTH, MAX_LINES = 62, 3          # body wrap width / max body lines
    IMP_W, IMP_LINES = 74, 2          # 'Do:' line width / max lines
    LINE_H = 0.0192                   # figure fraction per 8.6pt line
    HDR_H, PAD = 0.050, 0.012

    notes = parse_digest_notes(digest_text)
    guide = [it for it in items if it["kind"] in ("guideline", "consensus")][:5]
    study = [it for it in items
             if it["kind"] in ("trial", "meta-analysis", "systematic review")][:4]
    shown = {it["pmid"] for it in guide + study}
    rest = [it for it in items if it["pmid"] not in shown]

    fig = plt.figure(figsize=(16.0, 9.0), dpi=150)
    fig.patch.set_facecolor("#f7f9fb")
    ink, navy, teal, grey = "#1f2328", "#1e4e79", "#2e8b8b", "#5b6b7c"
    fig.patches.append(Rectangle((0.0, 0.902), 1.0, 0.098,
                                transform=fig.transFigure, facecolor="#12283d",
                                edgecolor="none", zorder=0))
    fig.text(0.025, 0.945, "GI & Hepatology Weekly",
             fontsize=20, weight="bold", color="white")
    fig.text(0.025, 0.915,
             "Guidelines, consensus statements and clinical studies newly "
             "indexed in PubMed", fontsize=10.5, color="#c8d6e2")
    kinds: dict = {}
    for it in items:
        kinds[it["kind"]] = kinds.get(it["kind"], 0) + 1
    singular = {"guideline": "guideline", "consensus": "consensus statement",
                "trial": "trial", "meta-analysis": "meta-analysis",
                "systematic review": "systematic review", "study": "study"}
    plural = {"guideline": "guidelines", "consensus": "consensus statements",
              "trial": "trials", "meta-analysis": "meta-analyses",
              "systematic review": "systematic reviews", "study": "studies"}
    mix = ", ".join(f"{v} {(singular if v == 1 else plural).get(k, k + 's')}"
                    for k, v in sorted(kinds.items()))
    fig.text(0.025, 0.876, f"{date_range}   |   {len(items)} items: {mix}",
             fontsize=10, color=grey)

    def trim(text: str) -> list:
        """Wrap to the body width and keep at most MAX_LINES lines."""
        out = wrap((text or "").strip(), WIDTH)
        if len(out) > MAX_LINES:
            out = out[:MAX_LINES]
            out[-1] = out[-1][:WIDTH - 1].rstrip() + "\u2026"
        return out

    def trim_impact(text: str) -> list:
        out = wrap((text or "").strip(), IMP_W)
        if len(out) > IMP_LINES:
            out = out[:IMP_LINES]
            out[-1] = out[-1][:IMP_W - 1].rstrip() + "\u2026"
        return out

    def card_height(body: str, impact: str) -> float:
        """Single source of truth for card geometry so the fit check and the
        drawing pass can never disagree (they did, and text spilled)."""
        ilines = trim_impact(impact)
        return (HDR_H + LINE_H * len(trim(body))
                + (PAD + LINE_H * len(ilines) if ilines else 0))

    def card(x: float, y: float, w: float, title: str, meta: str,
             body: str, impact: str) -> float:
        lines = trim(body)
        ilines = trim_impact(impact)
        h = card_height(body, impact)
        fig.patches.append(Rectangle((x, y - h), w, h,
                                    transform=fig.transFigure,
                                    facecolor="white", edgecolor="#e3e8ee",
                                    linewidth=1.0, zorder=1))
        fig.text(x + 0.012, y - 0.026, " ".join(wrap(title, 70)[:2]),
                 fontsize=10.2, weight="bold", color=navy, zorder=2,
                 linespacing=1.3)
        fig.text(x + 0.012, y - 0.047, meta[:86], fontsize=8, color=grey,
                 zorder=2)
        if lines:
            fig.text(x + 0.012, y - HDR_H - 0.004, "\n".join(lines),
                     fontsize=8.6, color=ink, va="top", linespacing=1.35,
                     zorder=2)
        if ilines:
            fig.text(x + 0.012, y - h + 0.008, "\n".join("Do: " + ilines[0]
                     if i == 0 else ilines[i] for i in range(len(ilines))),
                     fontsize=8.6, color=teal, weight="bold", zorder=2,
                     linespacing=1.3)
        return h

    left_x, right_x, col_w = 0.025, 0.512, 0.463
    fig.text(left_x, 0.845, "NEW GUIDANCE & CONSENSUS", fontsize=12,
             weight="bold", color=teal)
    fig.text(right_x, 0.845, "PIVOTAL TRIALS & META-ANALYSES", fontsize=12,
             weight="bold", color=teal)

    y = 0.826
    for it in guide:
        n = notes.get(it["pmid"], {})
        soc = SOCIETY_RE.search(it.get("title", "") + " " +
                                (it.get("abstract") or "")[:300])
        body = n.get("what") or (it.get("abstract") or "")[:300]
        h = card_height(body, n.get("impact", ""))
        if y - h < 0.070:
            fig.text(left_x, y - 0.028, f"+{len(guide) - guide.index(it)} "
                     f"more guidance item(s) listed in the email",
                     fontsize=9, color=grey, style="italic")
            break
        y -= card(left_x, y, col_w, n.get("title") or it.get("title", ""),
                  " · ".join(x for x in (
                      soc.group(1) if soc else "", it.get("journal", ""),
                      f"PMID {it['pmid']}") if x),
                  body, n.get("impact", "")) + 0.014

    y = 0.826
    for it in study:
        n = notes.get(it["pmid"], {})
        body = n.get("what") or (it.get("abstract") or "")[:300]
        h = card_height(body, n.get("impact", ""))
        if y - h < 0.070:
            fig.text(right_x, y - 0.028, f"+{len(study) - study.index(it)} "
                     f"more studies listed in the email", fontsize=9,
                     color=grey, style="italic")
            break
        y -= card(right_x, y, col_w, n.get("title") or it.get("title", ""),
                  f"{it.get('journal', '')} · {it['kind']} · PMID {it['pmid']}",
                  body, n.get("impact", "")) + 0.014

    if rest:
        also = "; ".join(f"{it.get('journal', '?')} PMID {it['pmid']}"
                         for it in rest[:5])
        fig.text(left_x, 0.052, "\n".join(wrap("Also in this window: " + also,
                                               150)), fontsize=8.4, color=grey)
    fig.text(left_x, 0.026,
             "Screening aid only — read the full text before changing "
             "practice. Every PMID links to PubMed in the email.",
             fontsize=8.4, color=grey, style="italic")
    fig.text(right_x, 0.026,
             f"rendered locally {datetime.now():%Y-%m-%d %H:%M} "
             f"(NotebookLM dashboard unavailable for this run)",
             fontsize=8.4, color=grey, ha="left")

    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, f"gihep_poster_{datetime.now():%Y%m%d-%H%M}.png")
    fig.savefig(out, facecolor=fig.get_facecolor())
    plt.close(fig)
    return out


# ── Infographic 2: NotebookLM dashboard ──────────────────────────────────────
NLM_ARTIFACTS = int(os.environ.get("NLM_ARTIFACTS") or 3)
NLM_MAX_SOURCES = int(os.environ.get("NLM_MAX_SOURCES") or 10)
NLM_GUIDE_SOURCES = int(os.environ.get("NLM_GUIDE_SOURCES") or 6)
NLM_STUDY_SOURCES = int(os.environ.get("NLM_STUDY_SOURCES") or 4)
# p-value handling: drop standalone "(p = 0.03)" groups first, then loose
# "..., p = 0.03" tokens, so the surrounding sentence keeps its brackets.
PVAL_GROUP_RE = re.compile(r"\(\s*p\s*[=<>]\s*0?\.\d+\s*\)", re.I)
PVAL_RE = re.compile(r"\s*[,;]?\s*\bp\s*[=<>]\s*0?\.\d+\b", re.I)


LATEX_MAP = {"\\ge": ">=", "\\le": "<=", "\\pm": "+/-", "\\times": "x",
             "\\%": "%", "\\&": chr(38), "\\sim": "~", "\\approx": "~"}


def _strip_stats(s: str) -> str:
    """Remove p-values and Gemini LaTeX leftovers.

    The digest prompt excludes p-values, and any that leak through get garbled
    by the artifact generator and paired with contradictory 'significant'
    claims; raw LaTeX ($\\ge$5.0) also renders as noise in the infographic."""
    s = s or ""
    for k, v in LATEX_MAP.items():
        s = s.replace(k, v)
    s = re.sub(r"\$+([^$]*)\$+", r"\1", s)
    s = PVAL_GROUP_RE.sub("", s)
    s = PVAL_RE.sub("", s)
    s = re.sub(r"\(\s*[,;]?\s*\)", "", s)      # empty parentheses
    s = re.sub(r"\(\s*[,;]\s*", "(", s)        # dangling separator
    s = re.sub(r"[,;]\s*\)", ")", s)            # dangling separator
    s = re.sub(r"\s*[,;]\s*([.;])", r"\1", s)
    s = re.sub(r"\b(and|or)\s*[,;]", ",", s)      # 'and p<0.001;' -> ','
    s = re.sub(r"\s+([,;%.])", r"\1", s)
    s = re.sub(r"\s{2,}", " ", s)
    return s.strip(" ,;.")


def parse_digest_notes(digest_text: str) -> dict:
    """digest markdown -> {pmid: {title, type, citation, what, impact, caveat}}.

    NotebookLM garbles numbers when it is fed raw abstracts, so the notebook
    sources carry these curated lines instead."""
    out: dict = {}
    for b in re.split(r"\n(?=###\s)", digest_text or ""):
        m = re.search(r"PMID\s+(\d{6,9})", b)
        if not m:
            continue
        title_m = re.match(r"###\s+(.*)", b.strip())

        def field(name: str, blk: str = b) -> str:
            fm = re.search(rf"\*\*{name}\*\*:\s*(.*)", blk)
            return _strip_stats(fm.group(1).strip()) if fm else ""

        out[m.group(1)] = {
            "title": (title_m.group(1).strip() if title_m else ""),
            "type": field("Type"),
            "citation": field("Citation"),
            "what": field("What it says"),
            "impact": field("Practice impact"),
            "caveat": field("Caveat"),
        }
    return out


NUM_RE = re.compile(r"\d|\bCI\b|\bHR\b|\bOR\b|\bRR\b|\bNNT\b|\bvs\b|%")


def _key_points(text: str, kind: str, n: int = 2, cap: int = 340) -> str:
    """Two sentences of substance; for studies prefer sentences carrying the
    headline numbers, otherwise the trial cards come out result-less."""
    parts = [p for p in re.split(r"(?<=[.;])\s+", (text or "").strip()) if p]
    if kind in ("trial", "meta-analysis", "systematic review"):
        numbered = [p for p in parts if NUM_RE.search(p)]
        parts = (numbered[:n] + [p for p in parts if p not in numbered])[:n] \
            if numbered else parts[:n]
    return " ".join(parts[:n])[:cap].strip()


def gihep_notebook_sources(items: list, digest_text: str,
                           cap: int | None = None) -> list:
    """Compact, curated per-item source blocks (guidance before studies)."""
    notes = parse_digest_notes(digest_text)
    ordered = sorted(items, key=lambda x: KIND_ORDER.get(x["kind"], 9))
    # Balanced selection so the notebook feeds BOTH infographic sections:
    # without this the guidance-heavy window starves the trials section and the
    # artifact drops it entirely.
    cap = cap or NLM_MAX_SOURCES
    if len(ordered) <= cap:
        picked = ordered          # a thematic dashboard keeps all its items
    else:
        guide = [it for it in ordered
                 if it["kind"] in ("guideline", "consensus")][:NLM_GUIDE_SOURCES]
        study = [it for it in ordered
                 if it["kind"] in ("trial", "meta-analysis", "systematic review")
                 ][:NLM_STUDY_SOURCES]
        picked = (guide + study)[:cap] or ordered[:cap]
    out = []
    for it in picked:
        n = notes.get(it["pmid"], {})
        soc = SOCIETY_RE.search(it.get("title", "") + " " +
                                (it.get("abstract") or "")[:300])
        lines = [
            f"TYPE: {n.get('type') or it['kind']}",
            f"SOCIETY: {soc.group(1) if soc else 'not stated'}",
            f"JOURNAL: {it.get('journal', '?')}",
            f"DATE: {it.get('date', '')}",
            f"PMID: {it['pmid']}",
            f"TITLE: {n.get('title') or it.get('title', '')}",
        ]
        if n.get("what"):
            kp = _key_points(n["what"], it["kind"])
            label = ("RESULT" if it["kind"] in ("trial", "meta-analysis",
                                               "systematic review")
                     else "KEY POINTS")
            lines.append(f"{label}: {kp}")
        if n.get("impact"):
            lines.append("PRACTICE: " + n["impact"][:220])
        if n.get("caveat"):
            lines.append("CAVEAT: " + n["caveat"][:180])
        if not n.get("what"):
            lines.append("ABSTRACT: " + _strip_stats(
                (it.get("abstract") or "")[:700]))
        out.append({"title": f"PMID {it['pmid']} — {it['kind']} — "
                             f"{(it.get('journal') or '')[:28]}",
                    "text": "\n".join(lines)})
    return out


LIVER_RE = re.compile(
    r"\b(hepat|liver|cirrhos|hcc|hepatocellular|biliary|cholest|mash|masld|"
    r"nafld|hbv|hcv|portal|varice|ascites|fibroscan|endoscop\w* varice)\b",
    re.I)


def plan_dashboards(items: list, max_c = None) -> list:
    """Split the window into thematic dashboards.

    One big artifact for the whole window forces the generator to cram, which
    is exactly where garble and dropped sections come from. Narrow dashboards
    let each one summarise deeply instead."""
    guide = [it for it in items if it["kind"] in ("guideline", "consensus")]
    study = [it for it in items
             if it["kind"] in ("trial", "meta-analysis", "systematic review")]
    plans = [
        {"key": "guidance", "notebook": "Guidance & Consensus",
         "caption": "New guidance & consensus — every recommendation in this "
                    "window's guidelines and expert statements (Gemini "
                    "NotebookLM)",
         "items": guide[:10]},
        {"key": "trials", "notebook": "Trials & Meta-analyses",
         "caption": "Pivotal trials & meta-analyses — populations, comparators "
                    "and the headline numbers (Gemini NotebookLM)",
         "items": study[:8]},
        {"key": "signals", "notebook": "Practice Signals",
         "caption": "Practice signals across the week — what to change, what to "
                    "verify, what to watch (Gemini NotebookLM)",
         "items": (guide[:5] + study[:4]
                   + [it for it in items if it not in guide + study][:3]),
         "cap": 12},
    ]
    return [pl for pl in plans if pl["items"]]


def dashboard_context(plan: dict, digest_text: str, date_range: str,
                      total_items: int) -> str:
    """Deep, tightly-scoped instructions for one dashboard."""
    head = (
        "Create ONE clinical infographic titled 'GI & Hepatology Weekly — "
        f"{plan['notebook']}' for hospital gastroenterologists and "
        "hepatologists. Use ONLY the attached sources. Never invent, "
        "translate, abbreviate or respell a society, journal, drug, disease or "
        "number; copy names and numbers exactly as written, and if a value is "
        "not in the sources omit it rather than guessing. Never print "
        "placeholders ('[Omitted]', 'N/A', 'TBD'). Copy every digit, "
        "percentage, confidence interval and acronym exactly; never round, "
        "recompute or restate a number, and never invent a value for a visual. "
        "Do NOT draw charts, bar meters, gauges or percentage rings — this is "
        "a text-and-icons layout. Do NOT show scores, ratings, rankings, GRADE "
        "letters or p-values of your own.\n"
        "HEADER STRIP: copy this line verbatim: "
        f"\"GI & Hepatology Weekly — {date_range} — {plan['notebook']} — "
        f"{len(plan['items'])} of {total_items} items this window\"\n"
        "Style: clean clinical editorial; light background (#f7f9fb), navy "
        "#1e4e79 and teal #2e8b8b accents, red only for cautions; large legible "
        "type, generous whitespace, wide margins so NO text is clipped by the "
        "image edge or overlaps the corner logo; landscape poster, flat "
        "vector.\n\n")
    if plan["key"] == "guidance":
        body = (
            "STRUCTURE — one card per source, 2 cards per row:\n"
            "• card header: issuing society (exactly as named) + journal "
            "abbreviation + PMID in small grey text\n"
            "• 'Applies to:' the population in max 10 words\n"
            "• 3 recommendation bullets of max 16 words each, taken from that "
            "source's KEY POINTS — the concrete recommendations, not background\n"
            "• 'Do:' one practice action in max 12 words\n"
            "• if the source states a strength/certainty or a monitoring "
            "interval, show it on its own line\n"
            "After the cards add a short footer band: 'Overlaps & differences:' "
            "one line naming any two sources that cover the same topic and how "
            "they differ, or 'no overlapping guidance this week'.\n")
    elif plan["key"] == "trials":
        body = (
            "STRUCTURE — one card per source, 2 cards per row:\n"
            "• card header: journal + study design (e.g. RCT, meta-analysis) + "
            "PMID\n"
            "• 'Population:' max 12 words incl. N if given\n"
            "• 'Intervention vs comparator:' max 14 words\n"
            "• 'Result:' the headline result copied from that source's RESULT "
            "line WITH its numbers (effect size, hazard/odds ratio with "
            "confidence interval, absolute difference, event counts)\n"
            "• 'So what:' the practice implication in max 12 words\n"
            "• where the source states it, add one line on follow-up duration "
            "or the key limitation\n"
            "Do not rank or grade the studies; present them in the order given.\n")
    else:
        body = (
            "STRUCTURE:\n"
            "• 'What to change now' — up to 4 bulbs, each naming the society or "
            "study and the concrete change, max 18 words\n"
            "• 'Verify before acting' — up to 3 lines naming claims that need "
            "the full text or are based on consensus/surrogate endpoints, max "
            "16 words each\n"
            "• 'Watch next' — 2 lines naming the questions this week's evidence "
            "leaves open, max 16 words each\n"
            "• 'Topic map' — a small grid of the week's themes (e.g. IBD, "
            "hepatitis B, endoscopy quality, hepatobiliary oncology, "
            "pancreatitis) with the journals that contributed, no numbers "
            "beyond counts of items\n")
    return head + body + "\nAttached source list:\n" + "\n".join(
        f"- [{it['kind']}] {it.get('journal', '?')} {it.get('date', '')} "
        f"PMID {it['pmid']} — {it.get('title', '')[:110]}"
        for it in plan["items"])


def _nlm_generate(di, nb: str, instructions: str, timeout: int = 420) -> str:
    """Generate a fresh artifact; fall back to the newest completed one.

    The vendored helper reuses today's artifact BEFORE generating, which is
    right for a daily digest but silently serves a stale image when the prompt
    or the sources just changed. Generate first here, and only fall back when
    the notebook's daily artifact cap is hit or the call errors.
    """
    for attempt in (1, 2):
        try:
            d = di._nlm(["art", "generate", "infographic", instructions,
                         "--wait", "-n", nb], timeout=timeout)
            url = d.get("url", "")
            if url:
                return url
            break
        except RuntimeError as e:
            msg = str(e)
            low = msg.lower()
            if "ratelimit" in low or "rate limit" in low:
                log("  NLM: daily artifact cap reached — reusing the latest "
                    "completed infographic")
                return _nlm_latest_infographic_url(di, nb)
            if attempt == 1 and ("authentication" in low
                                 or "unexpected_error" in low):
                try:
                    di._nlm(["auth", "init"], timeout=180)
                except Exception:
                    pass
                continue
            log(f"  NLM generate error: {msg[:180]}")
            break
    return _nlm_latest_infographic_url(di, nb)


def _nlm_latest_infographic_url(di, nb: str) -> str:
    """Fallback: newest completed Infographic in the notebook — covers both the
    daily artifact cap and a --wait that returns without a url."""
    try:
        d = di._nlm(["art", "list", "-n", nb])
        cands = [a for a in d.get("artifacts", [])
                 if a.get("type") == "Infographic"
                 and a.get("status") == "completed"]
        if not cands:
            return ""
        latest = max(cands, key=lambda a: a.get("created_at", ""))
        return di._nlm(["art", "get", latest["id"], "-n", nb]).get("url", "")
    except Exception as e:  # noqa: BLE001
        log(f"  NLM url fallback failed: {str(e)[:160]}")
        return ""


def make_notebooklm_infographics(items: list, digest_text: str,
                                 date_label: str,
                                 date_range: str = "") -> list:
    """Generate one deep NotebookLM dashboard per theme.

    Returns [{'key','label','path'}] for every dashboard that rendered."""
    try:
        import digest_infographic as di
    except Exception as e:  # noqa: BLE001
        log(f"  NLM: digest_infographic import failed: {e}")
        return []
    plans = plan_dashboards(items)[:max(1, NLM_ARTIFACTS)]
    out_list = []
    for plan in plans:
        title = (f"GI & Hepatology Weekly - {plan['notebook']} - {date_label}")
        try:
            nb = di.nlm_ensure_notebook(title)
            srcs = gihep_notebook_sources(plan["items"], digest_text,
                                          cap=plan.get("cap"))
            added = di.nlm_add_text_sources(nb, srcs)
            studies = sum(1 for x in srcs if "RESULT:" in x["text"])
            log(f"  NLM [{plan['key']}] notebook {nb}: {added}/{len(srcs)} "
                f"sources attached ({studies} with RESULT lines)")
            url = _nlm_generate(di, nb, dashboard_context(
                plan, digest_text, date_range, len(items)))
            if not url:
                url = _nlm_latest_infographic_url(di, nb)
            if not url:
                log(f"  NLM [{plan['key']}]: no artifact url returned")
                continue
            out = os.path.join(
                OUT_DIR,
                f"gihep_nlm_{plan['key']}_{datetime.now():%Y%m%d-%H%M}.png")
            di.nlm_download_image(url, out)
            log(f"  NLM [{plan['key']}] downloaded: {out}")
            out_list.append({"key": plan["key"], "label": plan["caption"],
                             "path": out})
        except Exception as e:  # noqa: BLE001
            log(f"  NLM [{plan['key']}] failed: {type(e).__name__}: "
                f"{str(e)[:200]}")
    return out_list


# ── Email ────────────────────────────────────────────────────────────────────
def _load_smtp_pass() -> str:
    p = os.environ.get("SMTP_PASS")
    if p:
        return p
    for cand in (os.path.expanduser("~/.hermes/secrets/smtp_app_password.txt"),
                 os.path.join(SCRIPT_DIR, "smtp_pass.txt")):
        try:
            with open(cand) as f:
                return f.read().strip()
        except FileNotFoundError:
            continue
    return ""


def send_email(subject: str, html_body: str,
               image_paths: list[str] | str | None = None,
               cids: list[str] | None = None) -> str:
    """Send the HTML email with inline CID images. Returns status string."""
    try:
        with open("/tmp/gihep_digest_email.html", "w") as f:
            f.write(html_body)
    except Exception:
        pass
    if os.environ.get("DIGEST_DRY_RUN", "").lower() in ("1", "true", "yes"):
        log(f"DRY RUN - email suppressed (would send: {subject})")
        return "dry-run"
    if not SMTP_USER or not RECIPIENT:
        log("ERROR: SMTP_USER/RECIPIENT not set — cannot send email")
        return "unconfigured"
    pas = _load_smtp_pass()
    if not pas:
        log("ERROR: no SMTP_PASS — cannot send email")
        return "unconfigured"
    if isinstance(image_paths, str):
        image_paths = [image_paths]
    image_paths = [p for p in (image_paths or []) if p and os.path.exists(p)]
    cids = cids or [f"infographic{i}" for i in range(len(image_paths))]
    if image_paths:
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText("GI & Hepatology Weekly — enable HTML to view.",
                            "plain", "utf-8"))
        alt.attach(MIMEText(html_body, "html", "utf-8"))
        msg = MIMEMultipart("related")
        msg.attach(alt)
        for i, ip in enumerate(image_paths):
            with open(ip, "rb") as fh:
                img = MIMEImage(fh.read())
            img.add_header("Content-ID", f"<{cids[i]}>")
            img.add_header("Content-Disposition", "inline",
                           filename=os.path.basename(ip))
            msg.attach(img)
    else:
        msg = MIMEMultipart("alternative")
        msg.attach(MIMEText(html_body, "html", "utf-8"))
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = RECIPIENT
    try:
        server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=45)
        server.login(SMTP_USER, pas)
        server.sendmail(SMTP_USER, [RECIPIENT], msg.as_string())
        server.quit()
        log(f"Email sent to {RECIPIENT} ({len(html_body)} chars, "
            f"{len(image_paths)} image(s))")
        return "sent"
    except Exception as e:  # noqa: BLE001
        log(f"ERROR sending email: {e}")
        return f"error: {e}"


def md_to_htmlish(text: str) -> str:
    """Markdown -> email-safe HTML. Escapes HTML first. Linkifies PMIDs and
    journal citations of the form 'PMID 12345678'."""
    esc = (text.replace("&", "&amp;").replace("<", "&lt;")
           .replace(">", "&gt;"))

    def _inline(s: str) -> str:
        s = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)",
                   r'<a href="\2">\1</a>', s)
        s = re.sub(r"(?<![/\d])PMID[:\s]*(\d{6,9})(?![\d/])",
                   r'PMID <a href="https://pubmed.ncbi.nlm.nih.gov/\1/">\1</a>',
                   s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", s)
        s = re.sub(r"(?<!\*)\*([^*\s][^*]*)\*(?!\*)", r"<i>\1</i>", s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        return s

    lines = []
    in_ul = False
    for raw in esc.splitlines():
        stripped = raw.rstrip().strip()
        if not stripped:
            if in_ul:
                lines.append("</ul>")
                in_ul = False
            lines.append("<br/>")
            continue
        m = re.match(r"^(#{1,4})\s+(.*)", stripped)
        if m:
            if in_ul:
                lines.append("</ul>")
                in_ul = False
            tag = "h3" if len(m.group(1)) <= 2 else "h4"
            lines.append(f"<{tag}>{_inline(m.group(2))}</{tag}>")
            continue
        m = re.match(r"^[-*]\s+(.*)", stripped)
        if m:
            if not in_ul:
                lines.append("<ul>")
                in_ul = True
            lines.append(f"<li>{_inline(m.group(1))}</li>")
            continue
        if in_ul:
            lines.append("</ul>")
            in_ul = False
        lines.append(_inline(stripped))
    if in_ul:
        lines.append("</ul>")
    return "<br/>".join(lines)


CSS = """
<style>
 body{font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
      color:#1f2328;line-height:1.55;max-width:820px;margin:0 auto;padding:16px;}
 h1{font-size:22px;border-bottom:2px solid #d0d7de;padding-bottom:8px;color:#12283d;}
 h3{color:#14506b;margin:16px 0 2px;font-size:16px;}
 h4{color:#2e8b8b;margin:12px 0 2px;font-size:14px;}
 li{margin:2px 0;}
 .meta{color:#57606a;font-size:13px;}
 a{color:#0969da;}
 ul{padding-left:20px;margin:4px 0 10px;}
 .infographic{width:100%;border-radius:10px;margin:12px 0 2px;
              border:1px solid #e3e8ee;}
 .cap{color:#57606a;font-size:12px;margin-bottom:14px;}
 .banner{background:#f2f7fa;border-left:4px solid #2e8b8b;padding:10px 12px;
         border-radius:6px;font-size:13px;margin:10px 0;}
 .also{font-size:13px;color:#33414f;}
 table{border-collapse:collapse;font-size:13px;}
 td,th{border:1px solid #e3e8ee;padding:4px 8px;text-align:left;}
</style>"""


def render_email(date_label: str, digest_text: str, items: list[dict],
                 also_indexed: list[dict], cids: list[str],
                 meta_note: str, labels: list | None = None) -> str:
    labels = labels or ["Evidence mix this week (rendered from the digest "
                        "data: type, journal and issuing-body counts)"]
    info = ""
    if cids:
        info = "<h4>At a glance</h4>"
        for i, cid in enumerate(cids):
            info += (f"<img class='infographic' src='cid:{cid}' "
                     f"alt='digest infographic {i+1}'/>")
            if i < len(labels):
                info += f"<div class='cap'>{labels[i]}</div>"
        info += "<hr/>"
    src_rows = "".join(
        f"<tr><td>{it['kind']}</td><td>{(it.get('journal') or '?')}</td>"
        f"<td>{it.get('date','')}</td>"
        f"<td><a href='https://pubmed.ncbi.nlm.nih.gov/{it['pmid']}/'>"
        f"PMID {it['pmid']}</a></td>"
        f"<td>{_html.escape((it.get('title') or '')[:110])}</td></tr>"
        for it in items)
    also = ""
    if also_indexed:
        rows = "".join(
            f"<li><a href='https://pubmed.ncbi.nlm.nih.gov/{it['pmid']}/'>"
            f"PMID {it['pmid']}</a> — {_html.escape((it.get('journal') or '?'))} "
            f"{it.get('date','')} — {_html.escape((it.get('title') or '')[:110])}"
            f" <span class='meta'>[{it['kind']}]</span></li>"
            for it in also_indexed[:BREAKING_LIMIT])
        also = (f"<h4>Also indexed this week (not analysed)</h4>"
                f"<ul class='also'>{rows}</ul>")
    return (f"<html><head><meta charset='utf-8'>{CSS}</head><body>"
            f"<h1>GI &amp; Hepatology Weekly</h1>"
            f"<div class='meta'>Guidelines, consensus statements and clinical "
            f"studies newly indexed in PubMed. Generated {date_label} by "
            f"Gemini Flash + Extended Thinking"
            + (f" ({_html.escape(meta_note)})" if meta_note else "")
            + f". Window: last {WINDOW_DAYS} days. "
            f"{len(items)} item(s) analysed.</div>"
            f"<div class='banner'>Ranking-free digest: every new guideline, "
            f"consensus statement, randomised trial and meta-analysis in "
            f"gastroenterology &amp; hepatology for this window is summarised "
            f"with its numbers and its practice implication.</div>"
            f"<hr/>{info}"
            f"{md_to_htmlish(digest_text)}"
            f"<hr/><h4>Items analysed this week</h4>"
            f"<table><tr><th>Type</th><th>Journal</th><th>Date</th>"
            f"<th>PMID</th><th>Title</th></tr>{src_rows}</table>"
            f"{also}"
            f"<hr/><div class='meta'>Sources: PubMed E-utilities "
            f"(guideline/consensus publication types, GI-hepatology journals, "
            f"GI-hepatology MeSH topics), Europe PMC as fallback. "
            f"Automated summary — verify full texts before changing practice."
            f"</div></body></html>")


def render_warn_email(date_label: str, detail: str) -> str:
    return (f"<html><head><meta charset='utf-8'>{CSS}</head><body>"
            f"<h1>GI &amp; Hepatology Weekly — no digest produced</h1>"
            f"<div class='banner'>The fetcher returned no items <b>and</b> at "
            f"least one source errored, so this is a WARN run rather than a "
            f"silently empty digest. {date_label}</div>"
            f"<h4>Errors</h4><pre>{_html.escape(detail[:3000])}</pre>"
            f"<div class='meta'>Re-run the workflow manually once the upstream "
            f"source is reachable (workflow_dispatch).</div></body></html>")


# ── Main ─────────────────────────────────────────────────────────────────────
def main() -> int:
    t_start = time.time()
    now = datetime.now(timezone.utc)
    end = now
    start = end - timedelta(days=WINDOW_DAYS)
    date_label = datetime.now().strftime("%Y-%m-%d")
    log(f"=== GI & Hepatology weekly digest starting "
        f"(window {WINDOW_DAYS}d, model {GEMINI_MODEL}+{GEMINI_THINKING}) ===")
    setup_auth_from_env()

    errors: list[str] = []
    items: list[dict] = []
    order = [FETCH_SOURCE] if FETCH_SOURCE in ("pubmed", "epmc") \
        else ["pubmed", "epmc"]
    for tier in order:
        try:
            log(f"Fetching via {tier} …")
            got, errs = (fetch_pubmed(start, end) if tier == "pubmed"
                         else fetch_epmc(start, end))
            errors += errs
            items += got
            log(f"  {tier}: {len(got)} item(s) ({len(errs)} error(s))")
        except Exception as e:  # noqa: BLE001
            msg = f"{tier} fetch crashed: {type(e).__name__}: {e}"
            log(f"  ERROR {msg}")
            errors.append(msg)
        if items and FETCH_SOURCE == "auto":
            break
    # If the primary tier returned a thin set, still try the fallback tier
    if items and FETCH_SOURCE == "auto" and len(items) < 5:
        try:
            log("Thin primary result — also querying europepmc …")
            got, errs = fetch_epmc(start, end)
            errors += errs
            known = {i["pmid"] for i in items}
            fresh = [g for g in got if g["pmid"] not in known]
            items += fresh
            log(f"  europepmc added {len(fresh)} item(s)")
        except Exception as e:  # noqa: BLE001
            log(f"  ERROR epmc supplement: {e}")

    seen = _load_seen()
    log(f"Seen-cache: {len(seen)} known PMID(s)")
    todo, dupes, dropped = select_items(items, seen)
    log(f"Fetched {len(items)} unique item(s); {len(dupes)} already reported; "
        f"{len(todo)} to analyse; {len(dropped)} over capacity")

    if not items:
        detail = "\n".join(errors) or "no errors reported — genuinely empty window"
        subj = f"GI & Hepatology Weekly — WARN (no items) {date_label}"
        body = render_warn_email(date_label, detail)
        send_email(subj, body)
        if errors:
            log("WARN run: no items and source errors — exit 2")
            return 2
        log("No items in window, no errors — exit 0")
        return 0

    if not todo:
        log("Nothing new since the last run — informational email only")
        body = render_email(
            date_label,
            "## Week in focus\n- No new guidelines, consensus statements or "
            "clinical studies were newly indexed for this window "
            "(everything fetched was already reported in a previous run).",
            [], [], [], "no new items")
        send_email(f"GI & Hepatology Weekly — no new items {date_label}", body)
        return 0

    analysis = analyze(todo)
    if not analysis["ok"]:
        detail = "\n".join(errors + analysis["errors"])
        log(f"Gemini analysis failed on every batch — WARN email. "
            f"{detail[:300]}")
        send_email(f"GI & Hepatology Weekly — WARN (analysis failed) {date_label}",
                   render_warn_email(date_label, detail))
        return 2

    meta_note = ", ".join(sorted({b for b in analysis["backends"] if b}))
    chart = ""
    try:
        chart = render_evidence_chart(todo, OUT_DIR)
        log(f"matplotlib chart: {chart}")
    except Exception as e:  # noqa: BLE001
        log(f"ERROR chart render: {type(e).__name__}: {e}")
    date_range = f"{start:%Y-%m-%d} to {end:%Y-%m-%d}"
    dashboards = make_notebooklm_infographics(todo, analysis["text"],
                                             date_label, date_range)
    labels = ["Evidence mix this week (rendered from the digest data: type, "
              "journal and issuing-body counts)"]
    if not dashboards:
        try:
            poster = render_clinical_poster(todo, analysis["text"],
                                            date_range, OUT_DIR)
            dashboards = [{"key": "poster", "path": poster,
                           "label": "Clinical summary poster rendered locally "
                                    "(NotebookLM dashboards unavailable this "
                                    "run)"}]
            log(f"poster fallback rendered: {poster}")
            meta_note = (meta_note + "; NotebookLM dashboards unavailable — "
                         "locally rendered clinical poster instead")
        except Exception as e:  # noqa: BLE001
            log(f"ERROR poster fallback: {type(e).__name__}: {e}")
            meta_note = meta_note + "; no summary infographic this run"
    labels += [d["label"] for d in dashboards]

    dash_paths = [d["path"] for d in dashboards]
    imgs = [p for p in ([chart] + dash_paths) if p]
    cids = [f"infographic{i}" for i in range(len(imgs))]
    body = render_email(date_label, analysis["text"], todo, dropped, cids,
                        meta_note, labels)
    subj = (f"GI & Hepatology Weekly — {len(todo)} item(s) "
            f"(guidelines, consensus & trials) {date_label}")
    status = send_email(subj, body, imgs, cids)

    if status == "sent":
        for it in todo:
            seen[it["pmid"]] = date_label
        seen = _prune_seen(seen)
        _save_seen(seen)
        log(f"Seen-cache updated: {len(seen)} entries")

    log(f"=== done in {time.time()-t_start:.0f}s — {len(todo)} analysed, "
        f"{len(imgs)} infographic(s), backend {meta_note}, email {status} ===")
    if analysis["errors"]:
        log(f"(partial batch failures: {analysis['errors']})")
        return 0 if len(analysis["errors"]) < max(1, len(todo) // BATCH_SIZE + 1) else 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
